language: php

php: 
    - "5.6"
    - "7.0"
    - hhvm
    - nightly

env:
    - SYMFONY_VERSION="2.8.*"
    - SYMFONY_VERSION="3.0.*"
    - SYMFONY_VERSION="3.1.*"

before_script:
    - composer require --no-update symfony/framework-bundle:${SYMFONY_VERSION}
    - composer install --prefer-source

script: bin/phpunit --coverage-clover clover.xml

after_script: bin/coveralls

branches:
    only: master

notifications:
    email: kevin@yappa.be
